# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  customize: !include scripts/customize.yaml


# Dir to custom themes
frontend:
  themes: !include themes/caule-themes-pack-1/caule-themes-pack-1.yaml

# Text to speech
tts:
  - platform: google_translate


# Redirects
group: !include scripts/groups.yaml
automation: !include scripts/automations.yaml
script: !include scripts/scripts.yaml
scene: !include scripts/scenes.yaml


# Networking
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5


# Direct to MosquitoMQTT Broker
mqtt:
  broker: 192.168.0.250


# Enable Python Scripts
python_script:      


# External Pi-Hole
pi_hole:
  - host: 192.168.0.2
    name: pihole
    api_key: !secret pihole_api
    
    
# Example Log file
logger: !include scripts/logger.yaml
  

# TP-Link Router
#device_tracker:
#  - platform: tplink_router
#    host: 192.168.0.1
#    username: admin
#    password: !secret tplink_router_password


# Samsung Smart TV
samsungtv:
  - host: 192.168.0.203
    name: "SamsungTV"


# Switch Components  
switch:
  - platform: mqtt
    unique_id: garage_relay_03
    name: "Garage Door 03"
    state_topic: "stat/voogie_relay_gd03/POWER"
    command_topic: "cmnd/voogie_relay_gd03/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"


# Binary Sensors    
binary_sensor:
  - platform: mqtt
    name: "Garage Door: Back"
    state_topic: "433/GarageDoor3"
    device_class: door
    qos: 1
    
  - platform: mqtt
    name: "Garage Door: JP"
    state_topic: "433/GarageDoor2"
    device_class: door
    qos: 1
    
  - platform: mqtt
    name: "Garage Door: Carin"
    state_topic: "433/GarageDoor1"
    device_class: door
    qos: 1


#OneWire Sensors    
sensor:
  - platform: onewire
    names:
      GENERATED_ID: OfficeTemp


# DSC Alarm with ESPHome  
alarm_control_panel: !include scripts/alarm.yaml


# Signal Notifications
notify:
  - name: signal
    platform: signal_messenger
    url: "http://192.168.0.250:8080" # the URL where the Signal Messenger REST API is listening
    number: "+27744335842" # the sender number
    recipients: # one or more recipients
      - "+27744335842"


# Important Dates
anniversaries:
  sensors:
  - name: Carin's Birthday
    date: !secret Carin_Birthday

  - name: JP's Birthday
    date: !secret JP_Birthday

  - name: Kaylee's Birthday
    date: !secret Kaylee_Birthday

  - name: Wedding Anniversary
    date: !secret Wedding_Anniversary


# Spotify
spotify:
  client_id: !secret Spotify_Client
  client_secret: !secret Spotify_Secret 