
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  customize: !include scripts/customize.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include scripts/groups.yaml
automation: !include scripts/automations.yaml
script: !include scripts/scripts.yaml
scene: !include scripts/scenes.yaml

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

mqtt:
  broker: 192.168.0.250

python_script:      
  
# Example Log file
logger:
  default: critical
  logs:
    # log level for HA core
    homeassistant.core: fatal

    # log level for MQTT integration
    homeassistant.components.mqtt: warning

    # log level for all python scripts
    homeassistant.components.python_script: debug

    # individual log level for this python script
    homeassistant.components.python_script.rfbridge_demux.py: debug

    # Not sure what this is, but it flooded the logs
    homeassistant.loader: warning
    homeassistant.setup: warning

    # log level for a custom component
    custom_components.my_integration: warning

    # log level for the `aiohttp` Python package
    aiohttp: error

    # log level for both 'glances_api' and 'glances' integration
    homeassistant.components.glances: fatal
    glances_api: fatal

# Switch Components  
switch:
  - platform: mqtt
    unique_id: garage_relay_03
    name: "Garage Door 03"
    state_topic: "stat/voogie_relay_gd03/POWER"
    command_topic: "cmnd/voogie_relay_gd03/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"

# Bianry Switches    
binary_sensor:
  - platform: mqtt
    name: "Garage Door: Back"
    state_topic: "433/GarageDoor3"
    device_class: door
    qos: 1
    
  - platform: mqtt
    name: "Garage Door: JP"
    state_topic: "433/GarageDoor2"
    device_class: door
    qos: 1
    
  - platform: mqtt
    name: "Garage Door: Carin"
    state_topic: "433/GarageDoor1"
    device_class: door
    qos: 1

#OneWire Sensors    
sensor:
  - platform: onewire
    names:
      GENERATED_ID: OfficeTemp

# DSC Alarm with ESPHome  
alarm_control_panel:
  - platform: template
    panels:
      safe_alarm_panel:
        name: "Alarm Panel"
        value_template: "{{states('sensor.dscalarm_partition_1_status')}}"
        code_arm_required: false
        
        arm_away:
          - service: esphome.dscalarm_alarm_arm_away
                  
        arm_home:
          - service: esphome.dscalarm_alarm_arm_home
          
        arm_night:
          - service: esphome.dscalarm_alarm_arm_night
            data_template:
              code: '{{code}}' #if you didnt set it in the yaml, then send the code here
          
        disarm:
          - service: esphome.dscalarm_alarm_disarm
            data_template:
              code: '{{code}}' 