
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include scripts/groups.yaml
automation: !include scripts/automations.yaml
script: !include scripts/scripts.yaml
scene: !include scripts/scenes.yaml

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

mqtt:
  broker: 192.168.0.250
  
switch:
  - platform: mqtt
    unique_id: garage_relay_03
    name: "Garage Door 03"
    state_topic: "stat/voogie_relay_gd03/POWER"
    command_topic: "cmnd/voogie_relay_gd03/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    
binary_sensor:
  - platform: mqtt
    name: "Garage Door 03"
    state_topic: "tele/voogie_rf_bridge/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "D08D0A"
    payload_off: "D08D0E"
    device_class: door
    qos: 1 
    
  - platform: mqtt
    name: "Garage Door 02"
    state_topic: "tele/voogie_rf_bridge/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "D1660A"
    payload_off: "D1660E"
    device_class: door
    qos: 1 
    
  - platform: mqtt
    name: "Garage Door 01"
    state_topic: "tele/voogie_rf_bridge/RESULT"
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "D1F80A"
    payload_off: "D1F80E"
    device_class: door
    qos: 1 
    
sensor:
  - platform: onewire
    names:
      GENERATED_ID: OfficeTemp
      
samsungtv:
  - host: 192.168.0.203  
    name: "Samsung Smart TV"
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: CC:B1:1A:90:E6:15
      