# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  customize: !include scripts/customize.yaml


# Dir to custom themes
frontend:
  themes: !include themes/caule-themes-pack-1/caule-themes-pack-1.yaml

# Text to speech
tts:
  - platform: google_translate


# Redirects
group: !include scripts/groups.yaml
automation: !include scripts/automations.yaml
script: !include scripts/scripts.yaml
scene: !include scripts/scenes.yaml


# Networking
http:
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5


# Direct to MosquitoMQTT Broker
mqtt:
  broker: 192.168.0.250


# Enable Python Scripts
python_script:      


# External Pi-Hole
pi_hole:
  - host: 192.168.0.2
    name: pihole
    api_key: !secret pihole_api
    
    
# Example Log file
logger: !include scripts/logger.yaml
  

# Speedtest
speedtestdotnet:
  scan_interval:
    minutes: 15


# TP-Link Router
#device_tracker:
#  - platform: tplink_router
#    host: 192.168.0.1
#    username: admin
#    password: !secret tplink_router_password


# Samsung Smart TV
samsungtv:
  - host: 192.168.0.203
    name: "SamsungTV"


# Switch Components  
switch:
  - platform: mqtt
    unique_id: garage_relay_03
    name: "Garage Door 03"
    state_topic: "stat/voogie_relay_gd03/POWER"
    command_topic: "cmnd/voogie_relay_gd03/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    
  - platform: mqtt
    unique_id: 3d_printer
    name: "3D Printer"
    state_topic: "stat/voogie_switch_3dprinter/POWER"
    command_topic: "cmnd/voogie_switch_3dprinter/POWER"
    qos: 1


# Binary Sensors    
binary_sensor:
  - platform: mqtt
    name: "Garage Door: Back"
    state_topic: "433/GarageDoor3"
    device_class: door
    qos: 1
    
  - platform: mqtt
    name: "Garage Door: JP"
    state_topic: "433/GarageDoor2"
    device_class: door
    qos: 1
    
  - platform: mqtt
    name: "Garage Door: Carin"
    state_topic: "433/GarageDoor1"
    device_class: door
    qos: 1
    
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error


#OneWire Sensors    
sensor:
  - platform: onewire
    names:
      GENERATED_ID: OfficeTemp
  - platform: template
    sensors:
      octoprint_time_elapsed_format:
        friendly_name: 'Printing Time Elapsed'
        value_template: >-
          {% set etime = states.sensor.printer_name_1_time_elapsed.state | int %}
          {% set seconds = etime % 60 %}
          {% set minutes = ((etime % 3600) / 60) | int %}
          {% set hours = ((etime % 86400) / 3600) | int %}
          {% set days = (etime / 86400) | int %}
          {%- if days > 0 -%}
            {%- if days == 1 -%}
              1 day
            {%- else -%}
              {{ days }} days
            {%- endif -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if hours > 0 -%}
            {%- if hours == 1 -%}
              1 hour
            {%- else -%}
              {{ hours }} hours
            {%- endif -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if minutes == 1 -%}
              1 minute
            {%- else -%}
              {{ minutes }} minutes
            {%- endif -%}
          {%- endif -%}
      octoprint_time_remaining_format:
        friendly_name: 'Printing Time Remaining'
        value_template: >-
          {% set rtime = states.sensor.printer_name_1_time_remaining.state | int %}
          {% set seconds = rtime % 60 %}
          {% set minutes = ((rtime % 3600) / 60) | int %}
          {% set hours = ((rtime % 86400) / 3600) | int %}
          {% set days = (rtime / 86400) | int %}
          {%- if days > 0 -%}
            {%- if days == 1 -%}
              1 day
            {%- else -%}
              {{ days }} days
            {%- endif -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if hours > 0 -%}
            {%- if hours == 1 -%}
              1 hour
            {%- else -%}
              {{ hours }} hours
            {%- endif -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if minutes == 1 -%}
              1 minute
            {%- else -%}
              {{ minutes }} minutes
            {%- endif -%}
          {%- endif -%}


# DSC Alarm with ESPHome  
alarm_control_panel: !include scripts/alarm.yaml


# Signal Notifications
notify:
  - name: signal
    platform: signal_messenger
    url: "http://192.168.0.250:8083" # the URL where the Signal Messenger REST API is listening
    number: "+27798984115" # the sender number
    recipients: # one or more recipients
      - "+27744335842"
      - "+27798928035"
  - name: signal_jp
    platform: signal_messenger
    url: "http://192.168.0.250:8083" # the URL where the Signal Messenger REST API is listening
    number: "+27798984115" # the sender number
    recipients: # one or more recipients
      - "+27744335842"
  - name: signal_carin
    platform: signal_messenger
    url: "http://192.168.0.250:8083" # the URL where the Signal Messenger REST API is listening
    number: "+27798984115" # the sender number
    recipients: # one or more recipients
      - "+27798928035"
  - name: signal_vernon
    platform: signal_messenger
    url: "http://192.168.0.250:8083" # the URL where the Signal Messenger REST API is listening
    number: "+27798984115" # the sender number
    recipients: # one or more recipients
      - "+27827580984"


# Important Dates
anniversaries:
  sensors:
  - name: Carin's Birthday
    date: !secret Carin_Birthday

  - name: JP's Birthday
    date: !secret JP_Birthday

  - name: Kaylee's Birthday
    date: !secret Kaylee_Birthday

  - name: Wedding Anniversary
    date: !secret Wedding_Anniversary


# Spotify
spotify:
  client_id: !secret Spotify_Client
  client_secret: !secret Spotify_Secret 
  
  
# OctoPrint
octoprint:
  host: 192.168.0.205
  api_key: !secret OctoPrint_api
  name: PRINTER_NAME_1
  number_of_tools: 1
  bed: true
  sensors:
    monitored_conditions:
      - 'Current State'
      - 'Job Percentage'
      - 'Temperatures'
      - 'Time Elapsed'
      - 'Time Remaining'
 

# Camera OctoPrint
camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://192.168.0.205/webcam/?action=snapshot
    mjpeg_url: http://192.168.0.205/webcam/?action=stream