- platform: template
  panels:
    safe_alarm_panel:
      name: "Alarm Panel"
      value_template: "{{states('sensor.dscalarm_partition_1_status')}}"
      code_arm_required: false
      
      arm_away:
        - service: esphome.dscalarm_alarm_arm_away
                
      arm_home:
        - service: esphome.dscalarm_alarm_arm_home
        
      arm_night:
        - service: esphome.dscalarm_alarm_arm_night
          data_template:
            code: '{{code}}' #if you didnt set it in the yaml, then send the code here
        
      disarm:
        - service: esphome.dscalarm_alarm_disarm
          data_template:
            code: '{{code}}' 